// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/movie.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DurationMin   int32                  `protobuf:"varint,3,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,4,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,5,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_proto_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMovieRequest) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *CreateMovieRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *CreateMovieRequest) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

type GetMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	mi := &file_proto_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DurationMin   int32                  `protobuf:"varint,4,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,5,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_proto_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMovieRequest) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *UpdateMovieRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *UpdateMovieRequest) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_proto_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesRequest) Reset() {
	*x = ListMoviesRequest{}
	mi := &file_proto_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesRequest) ProtoMessage() {}

func (x *ListMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesRequest.ProtoReflect.Descriptor instead.
func (*ListMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{7}
}

func (x *ListMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMoviesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DurationMin   int32                  `protobuf:"varint,4,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,5,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CacheHit      bool                   `protobuf:"varint,8,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieResponse) Reset() {
	*x = MovieResponse{}
	mi := &file_proto_movie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieResponse) ProtoMessage() {}

func (x *MovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieResponse.ProtoReflect.Descriptor instead.
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{8}
}

func (x *MovieResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieResponse) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *MovieResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *MovieResponse) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *MovieResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MovieResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

type ListMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*MovieResponse       `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesResponse) Reset() {
	*x = ListMoviesResponse{}
	mi := &file_proto_movie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesResponse) ProtoMessage() {}

func (x *ListMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesResponse.ProtoReflect.Descriptor instead.
func (*ListMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{9}
}

func (x *ListMoviesResponse) GetMovies() []*MovieResponse {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *ListMoviesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	HallId        int64                  `protobuf:"varint,2,opt,name=hall_id,json=hallId,proto3" json:"hall_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	DurationMin   int32                  `protobuf:"varint,4,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowtimeRequest) Reset() {
	*x = CreateShowtimeRequest{}
	mi := &file_proto_movie_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowtimeRequest) ProtoMessage() {}

func (x *CreateShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowtimeRequest.ProtoReflect.Descriptor instead.
func (*CreateShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{10}
}

func (x *CreateShowtimeRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *CreateShowtimeRequest) GetHallId() int64 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *CreateShowtimeRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateShowtimeRequest) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *CreateShowtimeRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeRequest) Reset() {
	*x = GetShowtimeRequest{}
	mi := &file_proto_movie_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeRequest) ProtoMessage() {}

func (x *GetShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{11}
}

func (x *GetShowtimeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowtimeRequest) Reset() {
	*x = DeleteShowtimeRequest{}
	mi := &file_proto_movie_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowtimeRequest) ProtoMessage() {}

func (x *DeleteShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowtimeRequest.ProtoReflect.Descriptor instead.
func (*DeleteShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteShowtimeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListShowtimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int64                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimesRequest) Reset() {
	*x = ListShowtimesRequest{}
	mi := &file_proto_movie_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimesRequest) ProtoMessage() {}

func (x *ListShowtimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimesRequest.ProtoReflect.Descriptor instead.
func (*ListShowtimesRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{13}
}

func (x *ListShowtimesRequest) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type ShowtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId       int64                  `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	HallId        int64                  `protobuf:"varint,3,opt,name=hall_id,json=hallId,proto3" json:"hall_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowtimeResponse) Reset() {
	*x = ShowtimeResponse{}
	mi := &file_proto_movie_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowtimeResponse) ProtoMessage() {}

func (x *ShowtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowtimeResponse.ProtoReflect.Descriptor instead.
func (*ShowtimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{14}
}

func (x *ShowtimeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShowtimeResponse) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *ShowtimeResponse) GetHallId() int64 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *ShowtimeResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ShowtimeResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShowtimeResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListShowtimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Showtimes     []*ShowtimeResponse    `protobuf:"bytes,1,rep,name=showtimes,proto3" json:"showtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimesResponse) Reset() {
	*x = ListShowtimesResponse{}
	mi := &file_proto_movie_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimesResponse) ProtoMessage() {}

func (x *ListShowtimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimesResponse.ProtoReflect.Descriptor instead.
func (*ListShowtimesResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{15}
}

func (x *ListShowtimesResponse) GetShowtimes() []*ShowtimeResponse {
	if x != nil {
		return x.Showtimes
	}
	return nil
}

type GetHallLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HallId        int64                  `protobuf:"varint,1,opt,name=hall_id,json=hallId,proto3" json:"hall_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHallLayoutRequest) Reset() {
	*x = GetHallLayoutRequest{}
	mi := &file_proto_movie_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHallLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallLayoutRequest) ProtoMessage() {}

func (x *GetHallLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallLayoutRequest.ProtoReflect.Descriptor instead.
func (*GetHallLayoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{16}
}

func (x *GetHallLayoutRequest) GetHallId() int64 {
	if x != nil {
		return x.HallId
	}
	return 0
}

type HallLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HallLayoutResponse) Reset() {
	*x = HallLayoutResponse{}
	mi := &file_proto_movie_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HallLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallLayoutResponse) ProtoMessage() {}

func (x *HallLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallLayoutResponse.ProtoReflect.Descriptor instead.
func (*HallLayoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{17}
}

func (x *HallLayoutResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HallLayoutResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HallLayoutResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *HallLayoutResponse) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ListHallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHallsRequest) Reset() {
	*x = ListHallsRequest{}
	mi := &file_proto_movie_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHallsRequest) ProtoMessage() {}

func (x *ListHallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHallsRequest.ProtoReflect.Descriptor instead.
func (*ListHallsRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{18}
}

type ListHallsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Halls         []*HallLayoutResponse  `protobuf:"bytes,1,rep,name=halls,proto3" json:"halls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHallsResponse) Reset() {
	*x = ListHallsResponse{}
	mi := &file_proto_movie_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHallsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHallsResponse) ProtoMessage() {}

func (x *ListHallsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHallsResponse.ProtoReflect.Descriptor instead.
func (*ListHallsResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_proto_rawDescGZIP(), []int{19}
}

func (x *ListHallsResponse) GetHalls() []*HallLayoutResponse {
	if x != nil {
		return x.Halls
	}
	return nil
}

var File_proto_movie_proto protoreflect.FileDescriptor

const file_proto_movie_proto_rawDesc = "" +
	"\n" +
	"\x11proto/movie.proto\x12\x05movie\"\a\n" +
	"\x05Empty\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb1\x01\n" +
	"\x12CreateMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fduration_min\x18\x03 \x01(\x05R\vdurationMin\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x04 \x01(\tR\tposterUrl\x12!\n" +
	"\frelease_date\x18\x05 \x01(\tR\vreleaseDate\"!\n" +
	"\x0fGetMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc1\x01\n" +
	"\x12UpdateMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fduration_min\x18\x04 \x01(\x05R\vdurationMin\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x05 \x01(\tR\tposterUrl\x12!\n" +
	"\frelease_date\x18\x06 \x01(\tR\vreleaseDate\"$\n" +
	"\x12DeleteMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x11ListMoviesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xf8\x01\n" +
	"\rMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fduration_min\x18\x04 \x01(\x05R\vdurationMin\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x05 \x01(\tR\tposterUrl\x12!\n" +
	"\frelease_date\x18\x06 \x01(\tR\vreleaseDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tcache_hit\x18\b \x01(\bR\bcacheHit\"X\n" +
	"\x12ListMoviesResponse\x12,\n" +
	"\x06movies\x18\x01 \x03(\v2\x14.movie.MovieResponseR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa3\x01\n" +
	"\x15CreateShowtimeRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\x12\x17\n" +
	"\ahall_id\x18\x02 \x01(\x03R\x06hallId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12!\n" +
	"\fduration_min\x18\x04 \x01(\x05R\vdurationMin\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"$\n" +
	"\x12GetShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"'\n" +
	"\x15DeleteShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x14ListShowtimesRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x03R\amovieId\"\xa6\x01\n" +
	"\x10ShowtimeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\x03R\amovieId\x12\x17\n" +
	"\ahall_id\x18\x03 \x01(\x03R\x06hallId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"N\n" +
	"\x15ListShowtimesResponse\x125\n" +
	"\tshowtimes\x18\x01 \x03(\v2\x17.movie.ShowtimeResponseR\tshowtimes\"/\n" +
	"\x14GetHallLayoutRequest\x12\x17\n" +
	"\ahall_id\x18\x01 \x01(\x03R\x06hallId\"`\n" +
	"\x12HallLayoutResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\x05R\x04cols\"\x12\n" +
	"\x10ListHallsRequest\"D\n" +
	"\x11ListHallsResponse\x12/\n" +
	"\x05halls\x18\x01 \x03(\v2\x19.movie.HallLayoutResponseR\x05halls2\x99\x06\n" +
	"\fMovieService\x12>\n" +
	"\vCreateMovie\x12\x19.movie.CreateMovieRequest\x1a\x14.movie.MovieResponse\x128\n" +
	"\bGetMovie\x12\x16.movie.GetMovieRequest\x1a\x14.movie.MovieResponse\x12>\n" +
	"\vUpdateMovie\x12\x19.movie.UpdateMovieRequest\x1a\x14.movie.MovieResponse\x126\n" +
	"\vDeleteMovie\x12\x19.movie.DeleteMovieRequest\x1a\f.movie.Empty\x12A\n" +
	"\n" +
	"ListMovies\x12\x18.movie.ListMoviesRequest\x1a\x19.movie.ListMoviesResponse\x12G\n" +
	"\x0eCreateShowtime\x12\x1c.movie.CreateShowtimeRequest\x1a\x17.movie.ShowtimeResponse\x12A\n" +
	"\vGetShowtime\x12\x19.movie.GetShowtimeRequest\x1a\x17.movie.ShowtimeResponse\x12<\n" +
	"\x0eDeleteShowtime\x12\x1c.movie.DeleteShowtimeRequest\x1a\f.movie.Empty\x12J\n" +
	"\rListShowtimes\x12\x1b.movie.ListShowtimesRequest\x1a\x1c.movie.ListShowtimesResponse\x12G\n" +
	"\rGetHallLayout\x12\x1b.movie.GetHallLayoutRequest\x1a\x19.movie.HallLayoutResponse\x12>\n" +
	"\tListHalls\x12\x17.movie.ListHallsRequest\x1a\x18.movie.ListHallsResponse\x125\n" +
	"\x06Health\x12\x14.movie.HealthRequest\x1a\x15.movie.HealthResponseB=Z;github.com/yourteam/cinema-system/movie-service/proto/movieb\x06proto3"

var (
	file_proto_movie_proto_rawDescOnce sync.Once
	file_proto_movie_proto_rawDescData []byte
)

func file_proto_movie_proto_rawDescGZIP() []byte {
	file_proto_movie_proto_rawDescOnce.Do(func() {
		file_proto_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_movie_proto_rawDesc), len(file_proto_movie_proto_rawDesc)))
	})
	return file_proto_movie_proto_rawDescData
}

var file_proto_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_movie_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: movie.Empty
	(*HealthRequest)(nil),         // 1: movie.HealthRequest
	(*HealthResponse)(nil),        // 2: movie.HealthResponse
	(*CreateMovieRequest)(nil),    // 3: movie.CreateMovieRequest
	(*GetMovieRequest)(nil),       // 4: movie.GetMovieRequest
	(*UpdateMovieRequest)(nil),    // 5: movie.UpdateMovieRequest
	(*DeleteMovieRequest)(nil),    // 6: movie.DeleteMovieRequest
	(*ListMoviesRequest)(nil),     // 7: movie.ListMoviesRequest
	(*MovieResponse)(nil),         // 8: movie.MovieResponse
	(*ListMoviesResponse)(nil),    // 9: movie.ListMoviesResponse
	(*CreateShowtimeRequest)(nil), // 10: movie.CreateShowtimeRequest
	(*GetShowtimeRequest)(nil),    // 11: movie.GetShowtimeRequest
	(*DeleteShowtimeRequest)(nil), // 12: movie.DeleteShowtimeRequest
	(*ListShowtimesRequest)(nil),  // 13: movie.ListShowtimesRequest
	(*ShowtimeResponse)(nil),      // 14: movie.ShowtimeResponse
	(*ListShowtimesResponse)(nil), // 15: movie.ListShowtimesResponse
	(*GetHallLayoutRequest)(nil),  // 16: movie.GetHallLayoutRequest
	(*HallLayoutResponse)(nil),    // 17: movie.HallLayoutResponse
	(*ListHallsRequest)(nil),      // 18: movie.ListHallsRequest
	(*ListHallsResponse)(nil),     // 19: movie.ListHallsResponse
}
var file_proto_movie_proto_depIdxs = []int32{
	8,  // 0: movie.ListMoviesResponse.movies:type_name -> movie.MovieResponse
	14, // 1: movie.ListShowtimesResponse.showtimes:type_name -> movie.ShowtimeResponse
	17, // 2: movie.ListHallsResponse.halls:type_name -> movie.HallLayoutResponse
	3,  // 3: movie.MovieService.CreateMovie:input_type -> movie.CreateMovieRequest
	4,  // 4: movie.MovieService.GetMovie:input_type -> movie.GetMovieRequest
	5,  // 5: movie.MovieService.UpdateMovie:input_type -> movie.UpdateMovieRequest
	6,  // 6: movie.MovieService.DeleteMovie:input_type -> movie.DeleteMovieRequest
	7,  // 7: movie.MovieService.ListMovies:input_type -> movie.ListMoviesRequest
	10, // 8: movie.MovieService.CreateShowtime:input_type -> movie.CreateShowtimeRequest
	11, // 9: movie.MovieService.GetShowtime:input_type -> movie.GetShowtimeRequest
	12, // 10: movie.MovieService.DeleteShowtime:input_type -> movie.DeleteShowtimeRequest
	13, // 11: movie.MovieService.ListShowtimes:input_type -> movie.ListShowtimesRequest
	16, // 12: movie.MovieService.GetHallLayout:input_type -> movie.GetHallLayoutRequest
	18, // 13: movie.MovieService.ListHalls:input_type -> movie.ListHallsRequest
	1,  // 14: movie.MovieService.Health:input_type -> movie.HealthRequest
	8,  // 15: movie.MovieService.CreateMovie:output_type -> movie.MovieResponse
	8,  // 16: movie.MovieService.GetMovie:output_type -> movie.MovieResponse
	8,  // 17: movie.MovieService.UpdateMovie:output_type -> movie.MovieResponse
	0,  // 18: movie.MovieService.DeleteMovie:output_type -> movie.Empty
	9,  // 19: movie.MovieService.ListMovies:output_type -> movie.ListMoviesResponse
	14, // 20: movie.MovieService.CreateShowtime:output_type -> movie.ShowtimeResponse
	14, // 21: movie.MovieService.GetShowtime:output_type -> movie.ShowtimeResponse
	0,  // 22: movie.MovieService.DeleteShowtime:output_type -> movie.Empty
	15, // 23: movie.MovieService.ListShowtimes:output_type -> movie.ListShowtimesResponse
	17, // 24: movie.MovieService.GetHallLayout:output_type -> movie.HallLayoutResponse
	19, // 25: movie.MovieService.ListHalls:output_type -> movie.ListHallsResponse
	2,  // 26: movie.MovieService.Health:output_type -> movie.HealthResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_movie_proto_init() }
func file_proto_movie_proto_init() {
	if File_proto_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_movie_proto_rawDesc), len(file_proto_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_movie_proto_goTypes,
		DependencyIndexes: file_proto_movie_proto_depIdxs,
		MessageInfos:      file_proto_movie_proto_msgTypes,
	}.Build()
	File_proto_movie_proto = out.File
	file_proto_movie_proto_goTypes = nil
	file_proto_movie_proto_depIdxs = nil
}
